In [ ]:
from tensorflow.keras.preprocessing import image

In [ ]:
img = image.load_img('/content/1163.jpg', target_size=(224,224))

In [ ]:
img_array = image.img_to_array(img)

In [ ]:
img_array.shape

(224, 224, 3)

In [ ]:
import numpy as np
expanded_img_array = np.expand_dims(img_array, axis=0)
print(expanded_img_array.shape)

(1, 224, 224, 3)


In [ ]:
#batch of images with 4D and this is expansion of 1 image
expanded_img_array

array([[[[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        ...,

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
       

In [ ]:
from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input

In [ ]:
import tensorflow
from tensorflow.keras.preprocessing import image
from tensorflow.keras.layers import GlobalMaxPooling2D


In [ ]:
model = ResNet50(weights='imagenet', include_top=False, input_shape=(224,224,3))
model.trainable = False

model = tensorflow.keras.Sequential([model,
                                     GlobalMaxPooling2D()
                                     ])

94765736/94765736 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
preprocessed_img = preprocess_input(expanded_img_array)
print(preprocessed_img.shape)
preprocessed_img

(1, 224, 224, 3)


array([[[[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        ...,

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,


In [ ]:
model.predict(preprocessed_img)

1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step


array([[ 1.6351323, 19.324389 ,  1.8080347, ...,  1.1685892, 17.43746  ,
        12.0990505]], dtype=float32)

In [ ]:
model.predict(preprocessed_img).flatten()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step


array([ 1.6351323, 19.324389 ,  1.8080347, ...,  1.1685892, 17.43746  ,
       12.0990505], dtype=float32)

In [ ]:

model.predict(preprocessed_img).flatten()/np.linalg.norm(model.predict(preprocessed_img).flatten())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step


array([0.00491865, 0.05812977, 0.00543876, ..., 0.00351524, 0.05245369,
       0.0363952 ], dtype=float32)

In [ ]:
from numpy.linalg import norm
norm(model.predict(preprocessed_img).flatten())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step


np.float32(332.43533)

In [ ]:
np.sqrt(np.dot(model.predict(preprocessed_img).flatten(),model.predict(preprocessed_img).flatten()))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step


np.float32(332.43533)